services:
  customer-app:
    image: polovyiivan/spring-customer-app:latest
    ports:
      - "8001:8001"
    build:
      context: ./spring-customer-app
      dockerfile: ./Dockerfile
      no_cache: true
      labels:
        label_name: "test-build"
      tags:
        - "spring-customer-app:latest"
        - "polovyiivan/spring-customer-app:latest"
